# Generated by Django 4.2.4 on 2023-08-18 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_movie', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='img',
            field=models.ImageField(default='annie', upload_to='files'),
            preserve_default=False,
        ),
    ]
