# Generated by Django 4.2.4 on 2023-09-04 04:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecomapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='price',
            field=models.DecimalField(decimal_places=2, default='1200', max_digits=10),
            preserve_default=False,
        ),
    ]
