# Generated by Django 4.2.4 on 2023-08-11 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newproapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img1', models.ImageField(upload_to='gallery')),
                ('name', models.CharField(max_length=200)),
                ('desc', models.TextField()),
            ],
        ),
    ]
