# Generated by Django 4.2.6 on 2023-10-25 17:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bankapp', '0003_branch_district_remove_employee_deptid_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='branch',
            old_name='empname',
            new_name='branchname',
        ),
        migrations.RenameField(
            model_name='branch',
            old_name='deptid',
            new_name='distid',
        ),
        migrations.RenameField(
            model_name='district',
            old_name='departmentname',
            new_name='districtname',
        ),
    ]
